import Navbar from '@/components/Navbar'
import './globals.css'
import { Noto_Sans } from 'next/font/google'
import Toast from '@/components/Toast'


export const metadata = {
  title: 'Jin GPT',
  description: 'Generated by create next app',
}
const font = Noto_Sans({ subsets: ['latin'],weight:['300','400','700','200','500'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} text-neutral-800 h-screen 
                          flex flex-col justify-between`}>
        <Toast/>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
